### ISSUE TITLE
ID Estimation on Swiss Roll (Global Scale) is off

### ISSUE THREAD

**Issue by h-spiess** [vittorioerba/pyFCI#4]
Hey,

Nice paper and thank you for the implementation in python. I'm comparing your estimator with another one (TwoNN (Facco et al., 2017 (https://doi.org/10.1038/s41598-017-11873-y))) especially for the use in understanding Deep Neural Networks' hidden activations.

Both estimators differ greatly in the estimated intrinsic dimension. That's why I started comparing both on simpler datasets, e.g., your estimator gives the correct ID for an embedded hypercube when TwoNN fails. But for the swiss roll your estimator is wrong and gives a id ≅ 3. This seems to differ from the results presented in your paper, although you used the swill roll in a slightly different setting. Have you tried your estimator on the swiss roll with only one global scale before?

This would be a simple reproducing code example:

```
import sklearn.datasets
import pyFCI

swiss_roll_data = sklearn.datasets.make_swiss_roll(n_samples=2000)
processed_dataset = pyFCI.center_and_normalize(swiss_roll_data[0])
fci = pyFCI.FCI(processed_dataset)
id = pyFCI.fit_FCI(fci)[0]
```

Is the swiss roll "too strongly curved" for the global scale use? If so, would you then recommend using the multi-scale FCI and pick the minimum ID as you described in the paper?

Thanks a lot :)

**Comment by vittorioerba** [comment]
Hi, thanks for looking into our work!

The FCI estimator is expected to perform poorly on curved dataset, and indeed you find that it estimates the embedding dimension in the case of the Swiss roll.
In this case it is crucial to use the multi-scale FCI.

**Comment by h-spiess** [comment]
Thanks a lot for that very fast answer :) I will try that :)
